query GetUsers {
	users {
		id
		email
		firstName
		lastName
		score
	}
}

query GetUserInlineFragment($id: ID!) {
	users(id: $id) {
		... on User {
			firstName
			lastName
		}
		email
	}
}

query getUsersConnection(
	$first: Int
	$after: String
	$last: Int
	$before: String
) {
	usersConnection(first: $first, after: $after, last: $last, before: $before) {
		edges {
			cursor
			node {
				id
				email
				firstName
				lastName
				score
			}
		}
		pageInfo {
			endCursor
			hasNextPage
			hasPreviousPage
			startCursor
		}
	}
}

mutation createUser($input: CreateUserInput!) {
	createUser(input: $input) {
		id
		email
		firstName
		lastName
	}
}

mutation updateUser($input: UpdateUserInput!) {
	updateUser(input: $input) {
		id
		firstName
		lastName
	}
}

mutation deleteUser($id: ID!) {
	deleteUser(id: $id)
}

subscription scoreChanged($id: ID) {
	scoreChanged(userId: $id) {
		id
		score
	}
}
